# Generated by Django 3.2.3 on 2021-05-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20210510_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer_can_loan',
            new_name='customer_has_loan',
        ),
    ]
