"""
Django settings for banking_system project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^asyky8fs&*z3axz96!k--4r)*l9^b*br#v_mv894gcgkljdir'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_mfa',
    'chat',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_app',
    'transaction_app',
    'accounts_app_account',
    'employee_app',
    'api',

    # 3rd party frameworks
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'celery',
    'celery_progress',
    'django_celery_beat',
    'rest_framework_swagger',
]

# IPFILTER_MIDDLEWARE =  {
#     'ALLOWED_IP_ADDRESSES': [
#         '127.0.0.1',
#     ]
# }

PRIVATE_PATHS = {
    'ONLY_FOR_EMPLOYEES' : [
        '/employee/overview_customers/',
        '/employee/edit_customer/<int:customer_id>/',
        '/employee/edit_customer_account/<int:customer_id>/<int:customer_account_id>/',
        '/employee/create_customer/',
        '/employee/create_customer_account/',
        '/employee/login/',
        '/employee/signup/'
    ]
}

# TASK QUEUES
CELERY_BROKER_URL = 'amqp://localhost'

# Manual scheduling Celery

CELERY_BEAT_SCHEDULE = {
    "scheduled_task": {
        "task": "api.tasks.update_rates",
        "schedule": 5.0
    },
    "scheduled_task": {
        "task": "api.tasks.update_currency_rates",
        "schedule": 5.0
    }
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# To utilize the database comment the above out and use:
# python3 -m celery -A banking_system worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
      'rest_framework.permissions.AllowAny',
   ],
#    'DEFAULT_AUTHENTICATION_CLASSES': [
#        'rest_framework.authentication.SessionAuthentication',
#       'rest_framework.authentication.TokenAuthentication',
#    ]
}

MIDDLEWARE = [
    'ipfilter_middleware.middleware.IPFilterMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_mfa.middleware.MfaMiddleware',
]

ROOT_URLCONF = 'banking_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'banking_system.wsgi.application'

ASGI_APPLICATION = 'banking_system.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
