# Generated by Django 3.1.7 on 2021-04-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('account_user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.profile')),
            ],
        ),
    ]
